### ISSUE TITLE
Multiagent learning

### ISSUE THREAD

**Issue by tcfuji** [elvisyjlin/lf2gym#2]
Hi,

Is it possible to do multiagent learning with this package (for example, training 4 DQN agents)? If so, any help is appreciated.

**Comment by elvisyjlin** [comment]
We didn't create an interface for multi-agent learning. The environment is based on [F.LF](https://github.com/Project-F/F.LF) which allows two player playing at the same client. Therefore, __multi-agent learning is possible if you modify the code__. Note that it only supports up to 2 players.

**Comment by tcfuji** [comment]
Thanks for responding! 

I'm not familiar with LF2 but just to be clear, it's a fighting game that supports up to 2 humans/learning agents that can have them fight against each other or up to 6 other bots provided by the LF2 game? Does this environment allow the human/agents to be allies when fighting against other bots?

Also, what's the difference between the `versusPlayer` and `duel` parameters?

**Comment by elvisyjlin** [comment]
Oh, you reminded that we did implement that multi-agent learning. I forgot it because it was not used in our research topic LOL. `versusPlayer` allows human play against the agent. When an agent is trained well, you can specify `versusPlayer=True` and load the trained model to play against the agent by yourself. `duel` is for multi-agent learning, where one agent plays against the other. The `step()` function takes two actions as inputs.

And yes, your understanding of the game is correct. If you'd like to try, you can play the game on its website https://github.com/Project-F/F.LF. The environment needs to be modified if you'd like to have more than 2 players at the same time because we only defined _normal mode_, _versusPlayer mode_, and _duel mode_. The maximum of total players in the battlefield is 8 whilst up to 2 players can be controlled by human or agent at the same time.

**Comment by tcfuji** [comment]
Great! Thanks for the help!
