### ISSUE TITLE
The game runs at 0 FPS and I do not understand why. I am trying this on the browser.

### ISSUE THREAD

**Issue by DNofulla** [elvisyjlin/lf2gym#4]

**Comment by DNofulla** [comment]
The game literally static

**Comment by elvisyjlin** [comment]
Hello @DNofulla,

Sorry for the late reply. Have you got any progress on solving the issue? If not, could you provide more information for me to reproduce the issue?

- What operating system you're using?
- What browser you're using to run the game?
- Is there any logs printed in the inspector console in your browser?

We use Chrome on Ubuntu when we were doing the experiment.

**Comment by elvisyjlin** [comment]
The game was stuck at fps 0 because the codebase was changed in the past year. `match.get_living_object();` was added in `LF2_19/AI/Crusher.js`, and that has conflicts with our modified javascript of the game.

I've fixed it with commit 7cb692c12339887848d864a1d9cbef1e07694c7e. Please remove the cloned game, and do the setup again to resolve the problem.

```bash
sudo rm -r F.LF
sh setup.sh
```

**Comment by DNofulla** [comment]
I have tried the fix you just implemented. Thank you very much for doing this! It works perfectly now, and I also now just figured out how to speed the FPS up as well for faster training. I wish you the best of luck, and again, thank you for solving this issue!
